# Generated by Django 4.2.27 on 2026-01-04 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routeprice',
            options={'ordering': ['route', 'semester']},
        ),
        migrations.RenameField(
            model_name='buspass',
            old_name='month',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='routeprice',
            old_name='month',
            new_name='semester',
        ),
        migrations.AlterUniqueTogether(
            name='routeprice',
            unique_together={('route', 'semester')},
        ),
    ]
