# Generated by Django 4.2.27 on 2026-01-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0002_alter_routeprice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buspass',
            name='semester',
            field=models.CharField(choices=[('Semester-1', 'Semester-1'), ('Semester-2', 'Semester-2'), ('Semester-3', 'Semester-3'), ('Semester-4', 'Semester-4'), ('Semester-5', 'Semester-5'), ('Semester-6', 'Semester-6')], max_length=20),
        ),
        migrations.AlterField(
            model_name='routeprice',
            name='semester',
            field=models.CharField(choices=[('Semester-1', 'Semester-1'), ('Semester-2', 'Semester-2'), ('Semester-3', 'Semester-3'), ('Semester-4', 'Semester-4'), ('Semester-5', 'Semester-5'), ('Semester-6', 'Semester-6')], max_length=20),
        ),
    ]
