# Generated by Django 4.2.27 on 2026-01-04 03:50

import buspass.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buspass', '0003_alter_buspass_semester_alter_routeprice_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSemesterBusPassApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semesters', models.TextField(help_text='List of continuous semesters selected, stored as JSON string')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for all semesters', max_digits=12)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to=buspass.models.upload_pass_receipt_path)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_multi_semester_passes', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_multi_semester_passes', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buspass.route')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_semester_applications', to='buspass.student')),
            ],
            options={
                'verbose_name': 'Multi-Semester Bus Pass Application',
                'verbose_name_plural': 'Multi-Semester Bus Pass Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
