# Generated by Django 4.2.27 on 2026-01-04 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0004_multisemesterbuspassapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='arrival_time_at_destination',
            field=models.TimeField(default='09:00', verbose_name='Arrival Time at Destination'),
        ),
        migrations.AddField(
            model_name='route',
            name='arrival_time_at_source',
            field=models.TimeField(default='08:00', verbose_name='Arrival Time at Source'),
        ),
        migrations.AddField(
            model_name='route',
            name='driver_contact',
            field=models.CharField(default='0000000000', max_length=15, validators=[django.core.validators.RegexValidator(message='Driver contact number must be 10 to 15 digits', regex='^\\d{10,15}$')], verbose_name='Driver Contact Number'),
        ),
        migrations.AddField(
            model_name='route',
            name='driver_name',
            field=models.CharField(default='TBD', max_length=100, verbose_name='Driver Name'),
        ),
    ]
